import csv

# Extended movie database with much more movies
movies_data = [
    # Classic Hollywood (1940s-1960s)
    {"movieId": "1", "title": "Casablanca (1942)", "genres": "Drama|Romance|War", "year": "1942", "rating": "8.5"},
    {"movieId": "2", "title": "Citizen Kane (1941)", "genres": "Drama|Mystery", "year": "1941", "rating": "8.3"},
    {"movieId": "3", "title": "The Wizard of Oz (1939)", "genres": "Adventure|Family|Fantasy|Musical", "year": "1939", "rating": "8.1"},
    {"movieId": "4", "title": "Gone with the Wind (1939)", "genres": "Drama|Romance|War", "year": "1939", "rating": "8.2"},
    {"movieId": "5", "title": "Lawrence of Arabia (1962)", "genres": "Adventure|Biography|Drama|History|War", "year": "1962", "rating": "8.3"},
    {"movieId": "6", "title": "The Bridge on the River Kwai (1957)", "genres": "Adventure|Drama|War", "year": "1957", "rating": "8.1"},
    {"movieId": "7", "title": "Some Like It Hot (1959)", "genres": "Comedy|Romance", "year": "1959", "rating": "8.2"},
    {"movieId": "8", "title": "Sunset Boulevard (1950)", "genres": "Drama|Film-Noir", "year": "1950", "rating": "8.4"},
    {"movieId": "9", "title": "The Apartment (1960)", "genres": "Comedy|Drama|Romance", "year": "1960", "rating": "8.3"},
    {"movieId": "10", "title": "North by Northwest (1959)", "genres": "Action|Adventure|Mystery|Thriller", "year": "1959", "rating": "8.3"},
    
    # Hitchcock Classics
    {"movieId": "11", "title": "Vertigo (1958)", "genres": "Mystery|Romance|Thriller", "year": "1958", "rating": "8.3"},
    {"movieId": "12", "title": "Psycho (1960)", "genres": "Horror|Mystery|Thriller", "year": "1960", "rating": "8.5"},
    {"movieId": "13", "title": "Rear Window (1954)", "genres": "Mystery|Thriller", "year": "1954", "rating": "8.5"},
    {"movieId": "14", "title": "The Birds (1963)", "genres": "Drama|Horror|Mystery", "year": "1963", "rating": "7.7"},
    {"movieId": "15", "title": "Dial M for Murder (1954)", "genres": "Crime|Thriller", "year": "1954", "rating": "8.2"},
    
    # 1970s Classics
    {"movieId": "16", "title": "The Godfather (1972)", "genres": "Crime|Drama", "year": "1972", "rating": "9.2"},
    {"movieId": "17", "title": "The Godfather Part II (1974)", "genres": "Crime|Drama", "year": "1974", "rating": "9.0"},
    {"movieId": "18", "title": "Apocalypse Now (1979)", "genres": "Drama|War", "year": "1979", "rating": "8.4"},
    {"movieId": "19", "title": "Taxi Driver (1976)", "genres": "Crime|Drama|Thriller", "year": "1976", "rating": "8.2"},
    {"movieId": "20", "title": "Chinatown (1974)", "genres": "Crime|Drama|Mystery|Thriller", "year": "1974", "rating": "8.2"},
    {"movieId": "21", "title": "The Exorcist (1973)", "genres": "Horror", "year": "1973", "rating": "8.1"},
    {"movieId": "22", "title": "Jaws (1975)", "genres": "Adventure|Drama|Thriller", "year": "1975", "rating": "8.1"},
    {"movieId": "23", "title": "Star Wars (1977)", "genres": "Action|Adventure|Fantasy|Sci-Fi", "year": "1977", "rating": "8.6"},
    {"movieId": "24", "title": "Annie Hall (1977)", "genres": "Comedy|Romance", "year": "1977", "rating": "8.0"},
    {"movieId": "25", "title": "Manhattan (1979)", "genres": "Comedy|Drama|Romance", "year": "1979", "rating": "7.9"},
    
    # 1980s
    {"movieId": "26", "title": "Raging Bull (1980)", "genres": "Biography|Drama|Sport", "year": "1980", "rating": "8.2"},
    {"movieId": "27", "title": "The Shining (1980)", "genres": "Drama|Horror", "year": "1980", "rating": "8.4"},
    {"movieId": "28", "title": "Raiders of the Lost Ark (1981)", "genres": "Action|Adventure", "year": "1981", "rating": "8.5"},
    {"movieId": "29", "title": "Blade Runner (1982)", "genres": "Action|Drama|Sci-Fi|Thriller", "year": "1982", "rating": "8.1"},
    {"movieId": "30", "title": "E.T. the Extra-Terrestrial (1982)", "genres": "Family|Sci-Fi", "year": "1982", "rating": "7.9"},
    {"movieId": "31", "title": "Scarface (1983)", "genres": "Crime|Drama", "year": "1983", "rating": "8.3"},
    {"movieId": "32", "title": "The Terminator (1984)", "genres": "Action|Sci-Fi", "year": "1984", "rating": "8.1"},
    {"movieId": "33", "title": "Amadeus (1984)", "genres": "Biography|Drama|History|Music", "year": "1984", "rating": "8.4"},
    {"movieId": "34", "title": "Back to the Future (1985)", "genres": "Adventure|Comedy|Sci-Fi", "year": "1985", "rating": "8.5"},
    {"movieId": "35", "title": "The Princess Bride (1987)", "genres": "Adventure|Comedy|Family|Fantasy|Romance", "year": "1987", "rating": "8.1"},
    {"movieId": "36", "title": "Die Hard (1988)", "genres": "Action|Thriller", "year": "1988", "rating": "8.2"},
    {"movieId": "37", "title": "Big (1988)", "genres": "Comedy|Drama|Fantasy|Romance", "year": "1988", "rating": "7.3"},
    {"movieId": "38", "title": "Rain Man (1988)", "genres": "Drama", "year": "1988", "rating": "8.0"},
    
    # 1990s
    {"movieId": "39", "title": "Goodfellas (1990)", "genres": "Biography|Crime|Drama", "year": "1990", "rating": "8.7"},
    {"movieId": "40", "title": "The Silence of the Lambs (1991)", "genres": "Crime|Drama|Thriller", "year": "1991", "rating": "8.6"},
    {"movieId": "41", "title": "Terminator 2: Judgment Day (1991)", "genres": "Action|Sci-Fi", "year": "1991", "rating": "8.6"},
    {"movieId": "42", "title": "JFK (1991)", "genres": "Drama|History|Thriller", "year": "1991", "rating": "8.0"},
    {"movieId": "43", "title": "Unforgiven (1992)", "genres": "Drama|Western", "year": "1992", "rating": "8.2"},
    {"movieId": "44", "title": "The Shawshank Redemption (1994)", "genres": "Drama", "year": "1994", "rating": "9.3"},
    {"movieId": "45", "title": "Pulp Fiction (1994)", "genres": "Crime|Drama", "year": "1994", "rating": "8.9"},
    {"movieId": "46", "title": "Forrest Gump (1994)", "genres": "Drama|Romance", "year": "1994", "rating": "8.8"},
    {"movieId": "47", "title": "The Lion King (1994)", "genres": "Animation|Adventure|Drama|Family|Musical", "year": "1994", "rating": "8.5"},
    {"movieId": "48", "title": "Speed (1994)", "genres": "Action|Adventure|Thriller", "year": "1994", "rating": "7.3"},
    {"movieId": "49", "title": "Se7en (1995)", "genres": "Crime|Drama|Mystery|Thriller", "year": "1995", "rating": "8.6"},
    {"movieId": "50", "title": "The Usual Suspects (1995)", "genres": "Crime|Mystery|Thriller", "year": "1995", "rating": "8.5"},
    {"movieId": "51", "title": "Heat (1995)", "genres": "Action|Crime|Drama", "year": "1995", "rating": "8.3"},
    {"movieId": "52", "title": "Casino (1995)", "genres": "Crime|Drama", "year": "1995", "rating": "8.2"},
    {"movieId": "53", "title": "Toy Story (1995)", "genres": "Animation|Adventure|Comedy|Family|Fantasy", "year": "1995", "rating": "8.3"},
    {"movieId": "54", "title": "Fargo (1996)", "genres": "Crime|Drama|Thriller", "year": "1996", "rating": "8.1"},
    {"movieId": "55", "title": "The Rock (1996)", "genres": "Action|Adventure|Thriller", "year": "1996", "rating": "7.4"},
    {"movieId": "56", "title": "Scream (1996)", "genres": "Horror|Mystery", "year": "1996", "rating": "7.4"},
    {"movieId": "57", "title": "The English Patient (1996)", "genres": "Drama|Romance|War", "year": "1996", "rating": "7.4"},
    {"movieId": "58", "title": "Titanic (1997)", "genres": "Drama|Romance", "year": "1997", "rating": "7.9"},
    {"movieId": "59", "title": "L.A. Confidential (1997)", "genres": "Crime|Drama|Mystery|Thriller", "year": "1997", "rating": "8.2"},
    {"movieId": "60", "title": "Good Will Hunting (1997)", "genres": "Drama|Romance", "year": "1997", "rating": "8.3"},
    {"movieId": "61", "title": "As Good as It Gets (1997)", "genres": "Comedy|Drama|Romance", "year": "1997", "rating": "7.7"},
    {"movieId": "62", "title": "Saving Private Ryan (1998)", "genres": "Drama|War", "year": "1998", "rating": "8.6"},
    {"movieId": "63", "title": "The Truman Show (1998)", "genres": "Comedy|Drama|Sci-Fi", "year": "1998", "rating": "8.2"},
    {"movieId": "64", "title": "There's Something About Mary (1998)", "genres": "Comedy|Romance", "year": "1998", "rating": "7.1"},
    {"movieId": "65", "title": "The Big Lebowski (1998)", "genres": "Comedy|Crime", "year": "1998", "rating": "8.1"},
    {"movieId": "66", "title": "American Beauty (1999)", "genres": "Drama", "year": "1999", "rating": "8.3"},
    {"movieId": "67", "title": "The Matrix (1999)", "genres": "Action|Sci-Fi", "year": "1999", "rating": "8.7"},
    {"movieId": "68", "title": "Fight Club (1999)", "genres": "Drama", "year": "1999", "rating": "8.8"},
    {"movieId": "69", "title": "The Sixth Sense (1999)", "genres": "Drama|Mystery|Thriller", "year": "1999", "rating": "8.2"},
    {"movieId": "70", "title": "Being John Malkovich (1999)", "genres": "Comedy|Drama|Fantasy", "year": "1999", "rating": "7.8"},
    
    # 2000s
    {"movieId": "71", "title": "Gladiator (2000)", "genres": "Action|Adventure|Drama", "year": "2000", "rating": "8.5"},
    {"movieId": "72", "title": "Memento (2000)", "genres": "Mystery|Thriller", "year": "2000", "rating": "8.4"},
    {"movieId": "73", "title": "Requiem for a Dream (2000)", "genres": "Drama", "year": "2000", "rating": "8.3"},
    {"movieId": "74", "title": "Cast Away (2000)", "genres": "Adventure|Drama|Romance", "year": "2000", "rating": "7.8"},
    {"movieId": "75", "title": "Almost Famous (2000)", "genres": "Adventure|Comedy|Drama|Music", "year": "2000", "rating": "7.9"},
    {"movieId": "76", "title": "Shrek (2001)", "genres": "Animation|Adventure|Comedy|Family|Fantasy|Romance", "year": "2001", "rating": "7.9"},
    {"movieId": "77", "title": "The Lord of the Rings: The Fellowship of the Ring (2001)", "genres": "Action|Adventure|Drama|Fantasy", "year": "2001", "rating": "8.8"},
    {"movieId": "78", "title": "Mulholland Drive (2001)", "genres": "Drama|Mystery|Thriller", "year": "2001", "rating": "7.9"},
    {"movieId": "79", "title": "A Beautiful Mind (2001)", "genres": "Biography|Drama", "year": "2001", "rating": "8.2"},
    {"movieId": "80", "title": "Monsters, Inc. (2001)", "genres": "Animation|Comedy|Family|Fantasy", "year": "2001", "rating": "8.1"},
    {"movieId": "81", "title": "The Royal Tenenbaums (2001)", "genres": "Comedy|Drama", "year": "2001", "rating": "7.6"},
    {"movieId": "82", "title": "Spider-Man (2002)", "genres": "Action|Adventure|Sci-Fi", "year": "2002", "rating": "7.4"},
    {"movieId": "83", "title": "The Lord of the Rings: The Two Towers (2002)", "genres": "Action|Adventure|Drama|Fantasy", "year": "2002", "rating": "8.7"},
    {"movieId": "84", "title": "Chicago (2002)", "genres": "Comedy|Crime|Musical", "year": "2002", "rating": "7.2"},
    {"movieId": "85", "title": "Catch Me If You Can (2002)", "genres": "Biography|Crime|Drama", "year": "2002", "rating": "8.1"},
    {"movieId": "86", "title": "Finding Nemo (2003)", "genres": "Animation|Adventure|Comedy|Family", "year": "2003", "rating": "8.2"},
    {"movieId": "87", "title": "The Lord of the Rings: The Return of the King (2003)", "genres": "Action|Adventure|Drama|Fantasy", "year": "2003", "rating": "9.0"},
    {"movieId": "88", "title": "Lost in Translation (2003)", "genres": "Comedy|Drama", "year": "2003", "rating": "7.7"},
    {"movieId": "89", "title": "Kill Bill: Vol. 1 (2003)", "genres": "Action|Crime|Thriller", "year": "2003", "rating": "8.2"},
    {"movieId": "90", "title": "Mystic River (2003)", "genres": "Crime|Drama|Mystery|Thriller", "year": "2003", "rating": "7.9"},
    {"movieId": "91", "title": "Eternal Sunshine of the Spotless Mind (2004)", "genres": "Drama|Romance|Sci-Fi", "year": "2004", "rating": "8.3"},
    {"movieId": "92", "title": "Kill Bill: Vol. 2 (2004)", "genres": "Action|Crime|Thriller", "year": "2004", "rating": "8.0"},
    {"movieId": "93", "title": "Sideways (2004)", "genres": "Comedy|Drama|Romance", "year": "2004", "rating": "7.5"},
    {"movieId": "94", "title": "The Incredibles (2004)", "genres": "Animation|Action|Adventure|Family", "year": "2004", "rating": "8.0"},
    {"movieId": "95", "title": "Crash (2004)", "genres": "Crime|Drama|Thriller", "year": "2004", "rating": "7.7"},
    {"movieId": "96", "title": "Million Dollar Baby (2004)", "genres": "Drama|Sport", "year": "2004", "rating": "8.1"},
    {"movieId": "97", "title": "Batman Begins (2005)", "genres": "Action|Crime|Drama", "year": "2005", "rating": "8.2"},
    {"movieId": "98", "title": "Sin City (2005)", "genres": "Action|Crime|Thriller", "year": "2005", "rating": "8.0"},
    {"movieId": "99", "title": "Walk the Line (2005)", "genres": "Biography|Drama|Music|Romance", "year": "2005", "rating": "7.8"},
    {"movieId": "100", "title": "The Departed (2006)", "genres": "Crime|Drama|Thriller", "year": "2006", "rating": "8.5"},
    {"movieId": "101", "title": "Little Miss Sunshine (2006)", "genres": "Comedy|Drama", "year": "2006", "rating": "7.8"},
    {"movieId": "102", "title": "The Prestige (2006)", "genres": "Drama|Mystery|Sci-Fi|Thriller", "year": "2006", "rating": "8.5"},
    {"movieId": "103", "title": "Pan's Labyrinth (2006)", "genres": "Drama|Fantasy|War", "year": "2006", "rating": "8.2"},
    {"movieId": "104", "title": "Casino Royale (2006)", "genres": "Action|Adventure|Thriller", "year": "2006", "rating": "8.0"},
    {"movieId": "105", "title": "There Will Be Blood (2007)", "genres": "Drama", "year": "2007", "rating": "8.2"},
    {"movieId": "106", "title": "No Country for Old Men (2007)", "genres": "Crime|Drama|Thriller", "year": "2007", "rating": "8.2"},
    {"movieId": "107", "title": "Juno (2007)", "genres": "Comedy|Drama", "year": "2007", "rating": "7.5"},
    {"movieId": "108", "title": "Ratatouille (2007)", "genres": "Animation|Comedy|Family", "year": "2007", "rating": "8.1"},
    {"movieId": "109", "title": "The Dark Knight (2008)", "genres": "Action|Crime|Drama|Thriller", "year": "2008", "rating": "9.0"},
    {"movieId": "110", "title": "WALL-E (2008)", "genres": "Animation|Adventure|Family|Sci-Fi", "year": "2008", "rating": "8.4"},
    {"movieId": "111", "title": "Slumdog Millionaire (2008)", "genres": "Drama|Romance", "year": "2008", "rating": "8.0"},
    {"movieId": "112", "title": "The Curious Case of Benjamin Button (2008)", "genres": "Drama|Fantasy|Romance", "year": "2008", "rating": "7.8"},
    {"movieId": "113", "title": "Gran Torino (2008)", "genres": "Drama", "year": "2008", "rating": "8.1"},
    {"movieId": "114", "title": "Up (2009)", "genres": "Animation|Adventure|Comedy|Drama|Family", "year": "2009", "rating": "8.3"},
    {"movieId": "115", "title": "Inglourious Basterds (2009)", "genres": "Adventure|Drama|War", "year": "2009", "rating": "8.3"},
    {"movieId": "116", "title": "District 9 (2009)", "genres": "Action|Sci-Fi|Thriller", "year": "2009", "rating": "7.9"},
    {"movieId": "117", "title": "Avatar (2009)", "genres": "Action|Adventure|Fantasy|Sci-Fi", "year": "2009", "rating": "7.9"},
    {"movieId": "118", "title": "The Hurt Locker (2008)", "genres": "Drama|Thriller|War", "year": "2008", "rating": "7.5"},
    
    # 2010s
    {"movieId": "119", "title": "Inception (2010)", "genres": "Action|Drama|Sci-Fi|Thriller", "year": "2010", "rating": "8.8"},
    {"movieId": "120", "title": "Toy Story 3 (2010)", "genres": "Animation|Adventure|Comedy|Family|Fantasy", "year": "2010", "rating": "8.3"},
    {"movieId": "121", "title": "The Social Network (2010)", "genres": "Biography|Drama", "year": "2010", "rating": "7.7"},
    {"movieId": "122", "title": "Black Swan (2010)", "genres": "Drama|Thriller", "year": "2010", "rating": "8.0"},
    {"movieId": "123", "title": "The King's Speech (2010)", "genres": "Biography|Drama|History", "year": "2010", "rating": "8.0"},
    {"movieId": "124", "title": "Shutter Island (2010)", "genres": "Mystery|Thriller", "year": "2010", "rating": "8.2"},
    {"movieId": "125", "title": "The Artist (2011)", "genres": "Comedy|Drama|Romance", "year": "2011", "rating": "7.9"},
    {"movieId": "126", "title": "Hugo (2011)", "genres": "Adventure|Drama|Family|Fantasy|Mystery", "year": "2011", "rating": "7.5"},
    {"movieId": "127", "title": "Midnight in Paris (2011)", "genres": "Comedy|Fantasy|Romance", "year": "2011", "rating": "7.7"},
    {"movieId": "128", "title": "Drive (2011)", "genres": "Action|Drama", "year": "2011", "rating": "7.8"},
    {"movieId": "129", "title": "The Avengers (2012)", "genres": "Action|Adventure|Sci-Fi", "year": "2012", "rating": "8.0"},
    {"movieId": "130", "title": "Django Unchained (2012)", "genres": "Drama|Western", "year": "2012", "rating": "8.4"},
    {"movieId": "131", "title": "Life of Pi (2012)", "genres": "Adventure|Drama|Fantasy", "year": "2012", "rating": "7.9"},
    {"movieId": "132", "title": "Argo (2012)", "genres": "Biography|Drama|Thriller", "year": "2012", "rating": "7.7"},
    {"movieId": "133", "title": "Silver Linings Playbook (2012)", "genres": "Comedy|Drama|Romance", "year": "2012", "rating": "7.7"},
    {"movieId": "134", "title": "Skyfall (2012)", "genres": "Action|Adventure|Thriller", "year": "2012", "rating": "7.8"},
    {"movieId": "135", "title": "12 Years a Slave (2013)", "genres": "Biography|Drama|History", "year": "2013", "rating": "8.1"},
    {"movieId": "136", "title": "Gravity (2013)", "genres": "Drama|Sci-Fi|Thriller", "year": "2013", "rating": "7.7"},
    {"movieId": "137", "title": "Her (2013)", "genres": "Drama|Romance|Sci-Fi", "year": "2013", "rating": "8.0"},
    {"movieId": "138", "title": "The Wolf of Wall Street (2013)", "genres": "Biography|Comedy|Crime|Drama", "year": "2013", "rating": "8.2"},
    {"movieId": "139", "title": "Frozen (2013)", "genres": "Animation|Adventure|Comedy|Family|Fantasy|Musical", "year": "2013", "rating": "7.4"},
    {"movieId": "140", "title": "Inside Llewyn Davis (2013)", "genres": "Comedy|Drama|Music", "year": "2013", "rating": "7.4"},
    {"movieId": "141", "title": "Birdman (2014)", "genres": "Comedy|Drama", "year": "2014", "rating": "7.7"},
    {"movieId": "142", "title": "Boyhood (2014)", "genres": "Drama", "year": "2014", "rating": "7.9"},
    {"movieId": "143", "title": "The Grand Budapest Hotel (2014)", "genres": "Adventure|Comedy|Crime", "year": "2014", "rating": "8.1"},
    {"movieId": "144", "title": "Interstellar (2014)", "genres": "Adventure|Drama|Sci-Fi", "year": "2014", "rating": "8.6"},
    {"movieId": "145", "title": "Whiplash (2014)", "genres": "Drama|Music", "year": "2014", "rating": "8.5"},
    {"movieId": "146", "title": "Gone Girl (2014)", "genres": "Drama|Mystery|Thriller", "year": "2014", "rating": "8.1"},
    {"movieId": "147", "title": "Guardians of the Galaxy (2014)", "genres": "Action|Adventure|Comedy|Sci-Fi", "year": "2014", "rating": "8.0"},
    {"movieId": "148", "title": "Mad Max: Fury Road (2015)", "genres": "Action|Adventure|Sci-Fi|Thriller", "year": "2015", "rating": "8.1"},
    {"movieId": "149", "title": "The Revenant (2015)", "genres": "Action|Adventure|Drama|Thriller", "year": "2015", "rating": "8.0"},
    {"movieId": "150", "title": "Spotlight (2015)", "genres": "Biography|Crime|Drama", "year": "2015", "rating": "8.1"},
    {"movieId": "151", "title": "Inside Out (2015)", "genres": "Animation|Adventure|Comedy|Drama|Family|Fantasy", "year": "2015", "rating": "8.1"},
    {"movieId": "152", "title": "Ex Machina (2014)", "genres": "Drama|Sci-Fi|Thriller", "year": "2014", "rating": "7.7"},
    {"movieId": "153", "title": "The Martian (2015)", "genres": "Adventure|Drama|Sci-Fi", "year": "2015", "rating": "8.0"},
    {"movieId": "154", "title": "Star Wars: The Force Awakens (2015)", "genres": "Action|Adventure|Sci-Fi", "year": "2015", "rating": "7.8"},
    {"movieId": "155", "title": "Room (2015)", "genres": "Drama|Thriller", "year": "2015", "rating": "8.1"},
    {"movieId": "156", "title": "Zootopia (2016)", "genres": "Animation|Adventure|Comedy|Crime|Family|Mystery", "year": "2016", "rating": "8.0"},
    {"movieId": "157", "title": "La La Land (2016)", "genres": "Comedy|Drama|Music|Romance", "year": "2016", "rating": "8.0"},
    {"movieId": "158", "title": "Moonlight (2016)", "genres": "Drama", "year": "2016", "rating": "7.4"},
    {"movieId": "159", "title": "Arrival (2016)", "genres": "Drama|Sci-Fi", "year": "2016", "rating": "7.9"},
    {"movieId": "160", "title": "Hell or High Water (2016)", "genres": "Crime|Drama|Thriller|Western", "year": "2016", "rating": "7.6"},
    {"movieId": "161", "title": "Manchester by the Sea (2016)", "genres": "Drama", "year": "2016", "rating": "7.8"},
    {"movieId": "162", "title": "Rogue One: A Star Wars Story (2016)", "genres": "Action|Adventure|Sci-Fi", "year": "2016", "rating": "7.8"},
    {"movieId": "163", "title": "The Shape of Water (2017)", "genres": "Adventure|Drama|Fantasy|Romance", "year": "2017", "rating": "7.3"},
    {"movieId": "164", "title": "Get Out (2017)", "genres": "Horror|Mystery|Thriller", "year": "2017", "rating": "7.7"},
    {"movieId": "165", "title": "Lady Bird (2017)", "genres": "Comedy|Drama", "year": "2017", "rating": "7.4"},
    {"movieId": "166", "title": "Three Billboards Outside Ebbing, Missouri (2017)", "genres": "Comedy|Crime|Drama", "year": "2017", "rating": "8.1"},
    {"movieId": "167", "title": "Dunkirk (2017)", "genres": "Action|Drama|History|Thriller|War", "year": "2017", "rating": "7.8"},
    {"movieId": "168", "title": "Blade Runner 2049 (2017)", "genres": "Action|Drama|Mystery|Sci-Fi|Thriller", "year": "2017", "rating": "8.0"},
    {"movieId": "169", "title": "Coco (2017)", "genres": "Animation|Adventure|Comedy|Family|Fantasy|Music", "year": "2017", "rating": "8.4"},
    {"movieId": "170", "title": "The Post (2017)", "genres": "Biography|Drama|History|Thriller", "year": "2017", "rating": "7.2"},
    {"movieId": "171", "title": "Black Panther (2018)", "genres": "Action|Adventure|Sci-Fi", "year": "2018", "rating": "7.3"},
    {"movieId": "172", "title": "A Star Is Born (2018)", "genres": "Drama|Music|Romance", "year": "2018", "rating": "7.6"},
    {"movieId": "173", "title": "Roma (2018)", "genres": "Drama", "year": "2018", "rating": "7.7"},
    {"movieId": "174", "title": "Green Book (2018)", "genres": "Biography|Comedy|Drama|Music", "year": "2018", "rating": "8.2"},
    {"movieId": "175", "title": "Bohemian Rhapsody (2018)", "genres": "Biography|Drama|Music", "year": "2018", "rating": "7.9"},
    {"movieId": "176", "title": "Vice (2018)", "genres": "Biography|Comedy|Drama|History", "year": "2018", "rating": "7.2"},
    {"movieId": "177", "title": "Spider-Man: Into the Spider-Verse (2018)", "genres": "Animation|Action|Adventure|Family|Sci-Fi", "year": "2018", "rating": "8.4"},
    {"movieId": "178", "title": "Avengers: Infinity War (2018)", "genres": "Action|Adventure|Sci-Fi", "year": "2018", "rating": "8.4"},
    {"movieId": "179", "title": "Mission: Impossible - Fallout (2018)", "genres": "Action|Adventure|Thriller", "year": "2018", "rating": "7.7"},
    {"movieId": "180", "title": "Eighth Grade (2018)", "genres": "Comedy|Drama", "year": "2018", "rating": "7.4"},
    {"movieId": "181", "title": "Parasite (2019)", "genres": "Comedy|Drama|Thriller", "year": "2019", "rating": "8.5"},
    {"movieId": "182", "title": "1917 (2019)", "genres": "Drama|War", "year": "2019", "rating": "8.2"},
    {"movieId": "183", "title": "Once Upon a Time in Hollywood (2019)", "genres": "Comedy|Drama", "year": "2019", "rating": "7.6"},
    {"movieId": "184", "title": "Joker (2019)", "genres": "Crime|Drama|Thriller", "year": "2019", "rating": "8.4"},
    {"movieId": "185", "title": "Avengers: Endgame (2019)", "genres": "Action|Adventure|Drama|Sci-Fi", "year": "2019", "rating": "8.4"},
    {"movieId": "186", "title": "Toy Story 4 (2019)", "genres": "Animation|Adventure|Comedy|Family|Fantasy", "year": "2019", "rating": "7.7"},
    {"movieId": "187", "title": "Ford v Ferrari (2019)", "genres": "Action|Biography|Drama|Sport", "year": "2019", "rating": "8.1"},
    {"movieId": "188", "title": "Little Women (2019)", "genres": "Drama|Romance", "year": "2019", "rating": "7.8"},
    {"movieId": "189", "title": "Jojo Rabbit (2019)", "genres": "Comedy|Drama|War", "year": "2019", "rating": "7.9"},
    {"movieId": "190", "title": "Knives Out (2019)", "genres": "Comedy|Crime|Drama|Mystery|Thriller", "year": "2019", "rating": "7.9"},
    
    # 2020s
    {"movieId": "191", "title": "Nomadland (2020)", "genres": "Drama", "year": "2020", "rating": "7.3"},
    {"movieId": "192", "title": "Soul (2020)", "genres": "Animation|Adventure|Comedy|Drama|Family|Fantasy|Music", "year": "2020", "rating": "8.0"},
    {"movieId": "193", "title": "Minari (2020)", "genres": "Drama", "year": "2020", "rating": "7.4"},
    {"movieId": "194", "title": "Sound of Metal (2019)", "genres": "Drama|Music", "year": "2019", "rating": "7.7"},
    {"movieId": "195", "title": "The Trial of the Chicago 7 (2020)", "genres": "Drama|History|Thriller", "year": "2020", "rating": "7.7"},
    {"movieId": "196", "title": "Mank (2020)", "genres": "Biography|Drama", "year": "2020", "rating": "6.8"},
    {"movieId": "197", "title": "Tenet (2020)", "genres": "Action|Sci-Fi|Thriller", "year": "2020", "rating": "7.3"},
    {"movieId": "198", "title": "Wonder Woman 1984 (2020)", "genres": "Action|Adventure|Fantasy", "year": "2020", "rating": "5.4"},
    {"movieId": "199", "title": "Mulan (2020)", "genres": "Action|Adventure|Drama|Family|Fantasy", "year": "2020", "rating": "5.7"},
    {"movieId": "200", "title": "CODA (2021)", "genres": "Comedy|Drama|Music", "year": "2021", "rating": "8.0"},
    {"movieId": "201", "title": "Dune (2021)", "genres": "Action|Adventure|Drama|Sci-Fi", "year": "2021", "rating": "8.0"},
    {"movieId": "202", "title": "The Power of the Dog (2021)", "genres": "Drama|Western", "year": "2021", "rating": "6.8"},
    {"movieId": "203", "title": "West Side Story (2021)", "genres": "Crime|Drama|Musical|Romance", "year": "2021", "rating": "7.1"},
    {"movieId": "204", "title": "King Richard (2021)", "genres": "Biography|Drama|Sport", "year": "2021", "rating": "7.5"},
    {"movieId": "205", "title": "Belfast (2021)", "genres": "Biography|Drama", "year": "2021", "rating": "7.2"},
    {"movieId": "206", "title": "Don't Look Up (2021)", "genres": "Comedy|Drama|Sci-Fi", "year": "2021", "rating": "7.2"},
    {"movieId": "207", "title": "Spider-Man: No Way Home (2021)", "genres": "Action|Adventure|Fantasy|Sci-Fi", "year": "2021", "rating": "8.2"},
    {"movieId": "208", "title": "The Matrix Resurrections (2021)", "genres": "Action|Sci-Fi", "year": "2021", "rating": "5.7"},
    {"movieId": "209", "title": "No Time to Die (2021)", "genres": "Action|Adventure|Thriller", "year": "2021", "rating": "7.3"},
    {"movieId": "210", "title": "Encanto (2021)", "genres": "Animation|Comedy|Family|Fantasy|Musical", "year": "2021", "rating": "7.2"},
    {"movieId": "211", "title": "Everything Everywhere All at Once (2022)", "genres": "Action|Adventure|Comedy|Fantasy|Sci-Fi", "year": "2022", "rating": "7.8"},
    {"movieId": "212", "title": "The Banshees of Inisherin (2022)", "genres": "Comedy|Drama", "year": "2022", "rating": "7.7"},
    {"movieId": "213", "title": "Tár (2022)", "genres": "Drama|Music", "year": "2022", "rating": "7.4"},
    {"movieId": "214", "title": "The Fabelmans (2022)", "genres": "Drama", "year": "2022", "rating": "7.5"},
    {"movieId": "215", "title": "Women Talking (2022)", "genres": "Drama", "year": "2022", "rating": "6.9"},
    {"movieId": "216", "title": "Avatar: The Way of Water (2022)", "genres": "Action|Adventure|Drama|Fantasy|Sci-Fi", "year": "2022", "rating": "7.6"},
    {"movieId": "217", "title": "Top Gun: Maverick (2022)", "genres": "Action|Drama", "year": "2022", "rating": "8.3"},
    {"movieId": "218", "title": "Elvis (2022)", "genres": "Biography|Drama|Music", "year": "2022", "rating": "7.3"},
    {"movieId": "219", "title": "The Batman (2022)", "genres": "Action|Crime|Drama|Mystery|Thriller", "year": "2022", "rating": "7.8"},
    {"movieId": "220", "title": "Turning Red (2022)", "genres": "Animation|Adventure|Comedy|Drama|Family|Fantasy", "year": "2022", "rating": "7.0"},
    {"movieId": "221", "title": "Nope (2022)", "genres": "Horror|Mystery|Sci-Fi|Thriller", "year": "2022", "rating": "6.8"},
    {"movieId": "222", "title": "Glass Onion: A Knives Out Mystery (2022)", "genres": "Comedy|Crime|Drama|Mystery|Thriller", "year": "2022", "rating": "7.1"},
    {"movieId": "223", "title": "Black Adam (2022)", "genres": "Action|Fantasy|Sci-Fi", "year": "2022", "rating": "6.2"},
    {"movieId": "224", "title": "Wakanda Forever (2022)", "genres": "Action|Adventure|Drama|Sci-Fi", "year": "2022", "rating": "6.7"},
    {"movieId": "225", "title": "Babylon (2022)", "genres": "Comedy|Drama|History", "year": "2022", "rating": "7.1"},
    
    # Horror Classics
    {"movieId": "226", "title": "The Exorcist (1973)", "genres": "Horror", "year": "1973", "rating": "8.1"}, # Duplicado, mas ok para exemplo
    {"movieId": "227", "title": "Halloween (1978)", "genres": "Horror|Thriller", "year": "1978", "rating": "7.7"},
    {"movieId": "228", "title": "A Nightmare on Elm Street (1984)", "genres": "Horror", "year": "1984", "rating": "7.4"},
    {"movieId": "229", "title": "Friday the 13th (1980)", "genres": "Horror|Mystery|Thriller", "year": "1980", "rating": "6.4"},
    {"movieId": "230", "title": "The Thing (1982)", "genres": "Horror|Mystery|Sci-Fi", "year": "1982", "rating": "8.2"},
    {"movieId": "231", "title": "Alien (1979)", "genres": "Horror|Sci-Fi", "year": "1979", "rating": "8.5"},
    {"movieId": "232", "title": "Poltergeist (1982)", "genres": "Horror|Thriller", "year": "1982", "rating": "7.3"},
    {"movieId": "233", "title": "The Texas Chain Saw Massacre (1974)", "genres": "Horror", "year": "1974", "rating": "7.4"},
    {"movieId": "234", "title": "Rosemary's Baby (1968)", "genres": "Drama|Horror", "year": "1968", "rating": "8.0"},
    {"movieId": "235", "title": "The Omen (1976)", "genres": "Horror|Mystery", "year": "1976", "rating": "7.5"},
    
    # Sci-Fi Classics
    {"movieId": "236", "title": "2001: A Space Odyssey (1968)", "genres": "Adventure|Sci-Fi", "year": "1968", "rating": "8.3"},
    {"movieId": "237", "title": "Close Encounters of the Third Kind (1977)", "genres": "Drama|Sci-Fi", "year": "1977", "rating": "7.6"},
    {"movieId": "238", "title": "E.T. the Extra-Terrestrial (1982)", "genres": "Family|Sci-Fi", "year": "1982", "rating": "7.9"}, # Duplicado
    {"movieId": "239", "title": "The Day the Earth Stood Still (1951)", "genres": "Drama|Sci-Fi|Thriller", "year": "1951", "rating": "7.7"},
    {"movieId": "240", "title": "Forbidden Planet (1956)", "genres": "Adventure|Sci-Fi", "year": "1956", "rating": "7.6"},
    {"movieId": "241", "title": "Metropolis (1927)", "genres": "Drama|Sci-Fi", "year": "1927", "rating": "8.3"},
    {"movieId": "242", "title": "Planet of the Apes (1968)", "genres": "Adventure|Sci-Fi", "year": "1968", "rating": "8.0"},
    {"movieId": "243", "title": "The War of the Worlds (1953)", "genres": "Action|Sci-Fi|Thriller", "year": "1953", "rating": "7.0"},
    {"movieId": "244", "title": "Invasion of the Body Snatchers (1978)", "genres": "Horror|Sci-Fi", "year": "1978", "rating": "7.4"},
    {"movieId": "245", "title": "They Live (1988)", "genres": "Action|Horror|Sci-Fi|Thriller", "year": "1988", "rating": "7.3"},
    
    # Comedy Classics
    {"movieId": "246", "title": "The Gold Rush (1925)", "genres": "Adventure|Comedy|Drama", "year": "1925", "rating": "8.2"},
    {"movieId": "247", "title": "City Lights (1931)", "genres": "Comedy|Drama|Romance", "year": "1931", "rating": "8.5"},
    {"movieId": "248", "title": "Modern Times (1936)", "genres": "Comedy|Drama|Family|Romance", "year": "1936", "rating": "8.5"},
    {"movieId": "249", "title": "The Great Dictator (1940)", "genres": "Comedy|Drama|War", "year": "1940", "rating": "8.4"},
    {"movieId": "250", "title": "Duck Soup (1933)", "genres": "Comedy|Musical", "year": "1933", "rating": "7.7"}
]

def create_movies_csv():
    """Create movies.csv file with extended movie data"""
    fieldnames = ['movieId', 'title', 'genres', 'year', 'rating']
    
    with open('movies.csv', 'w', newline='', encoding='utf-8') as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        
        for movie in movies_data:
            writer.writerow(movie)
    
    print(f"Created movies.csv with {len(movies_data)} movies")

if __name__ == "__main__":
    create_movies_csv()
